#!/bin/bash

year=$1
systematic=$2

if [ "${year}" -eq "2016" ]
then
	data="Data_MET_2016,"
fi

if [ "${year}" -eq "2017" ]
then
	data="Data_MET_2017_BE,Data_MET_2017_F,"
fi

if [ "${year}" -eq "2018" ]
then
	data="Data_MET_2018_PreHEM,Data_MET_2018_PostHEM,"
fi

if [ -n "${systematic}" ]
then
	data=""
	systarg="-S ${systematic}"
fi

echo ${year}

echo ${data}

echo ${systematic}

python condorSubmit.py -d ${data} -n 1 -y ${year} ${systarg}
